-- MySQL Script generated by MySQL Workbench
-- Sun Feb 17 12:08:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rede-social2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rede-social2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rede-social2` ;
USE `rede-social2` ;

-- -----------------------------------------------------
-- Table `rede-social2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `rsenha` VARCHAR(30) NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `data_de_nascimento` DATE NULL,
  `telefone` INT(11) NULL,
  `genero` VARCHAR(45) NULL,
  `nome_social` VARCHAR(45) NULL,
  `data_criacao` DATE NULL,
  `situacao` TINYINT(1) NOT NULL DEFAULT 1,
  `foto_perfil` MEDIUMBLOB NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social2`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`chat` (
  `idchat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mensagem` LONGTEXT NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idchat`),
  INDEX `fk_chat_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_chat_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social2`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`grupo` (
  `idgrupo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_grupo` INT NOT NULL,
  `foto_do_grupo` MEDIUMBLOB NULL,
  `situação` TINYINT(1) NOT NULL,
  `chat_idchat` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idgrupo`),
  INDEX `fk_grupo_chat1_idx` (`chat_idchat` ASC),
  CONSTRAINT `fk_grupo_chat1`
    FOREIGN KEY (`chat_idchat`)
    REFERENCES `rede-social2`.`chat` (`idchat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social2`.`amizade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`amizade` (
  `idamizade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idamizade_amigo` INT UNSIGNED NOT NULL,
  `data_solicitacao` DATE NOT NULL,
  `data_confirmacao` DATE NOT NULL,
  `tipo_amigo` VARCHAR(45) NULL,
  PRIMARY KEY (`idamizade`, `idamizade_amigo`),
  INDEX `fk_amizade_usuario1_idx` (`idamizade` ASC),
  CONSTRAINT `fk_amizade_usuario1`
    FOREIGN KEY (`idamizade`)
    REFERENCES `rede-social2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social2`.`Paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`Paginas` (
  `idPaginas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `datainicio` VARCHAR(45) NULL,
  `sobre` MEDIUMTEXT NULL,
  `mebros` INT NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPaginas`),
  INDEX `fk_Paginas_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_Paginas_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social2`.`albuns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`albuns` (
  `idalbuns` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_foto` VARCHAR(100) NOT NULL,
  `local_foto` MEDIUMBLOB NOT NULL,
  `Paginas_idPaginas` INT NOT NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idalbuns`),
  INDEX `fk_albuns_Paginas1_idx` (`Paginas_idPaginas` ASC),
  INDEX `fk_albuns_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_albuns_Paginas1`
    FOREIGN KEY (`Paginas_idPaginas`)
    REFERENCES `rede-social2`.`Paginas` (`idPaginas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albuns_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social2`.`usuario_e_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`usuario_e_grupo` (
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  `grupo_idgrupo` INT UNSIGNED NOT NULL,
  `data_entraga` DATE NOT NULL,
  `administrador` INT NOT NULL,
  `membros` INT NULL,
  PRIMARY KEY (`usuario_idusuario`, `grupo_idgrupo`),
  INDEX `fk_usuario_has_grupo_grupo1_idx` (`grupo_idgrupo` ASC),
  INDEX `fk_usuario_has_grupo_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_grupo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_grupo_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `rede-social2`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social2`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social2`.`postagem` (
  `idpostagem` INT NOT NULL AUTO_INCREMENT,
  `postagem-texto` LONGTEXT NULL,
  `postagem-imagem` MEDIUMBLOB NULL,
  `postagem-video` LONGBLOB NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  `Paginas_idPaginas` INT NOT NULL,
  PRIMARY KEY (`idpostagem`),
  INDEX `fk_postagem_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_postagem_Paginas1_idx` (`Paginas_idPaginas` ASC),
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagem_Paginas1`
    FOREIGN KEY (`Paginas_idPaginas`)
    REFERENCES `rede-social2`.`Paginas` (`idPaginas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
