-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 16:34:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rede-social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rede-social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rede-social` ;
USE `rede-social` ;

-- -----------------------------------------------------
-- Table `rede-social`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `rsenha` VARCHAR(30) NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `data_de_nascimento` VARCHAR(11) NULL,
  `telefone` VARCHAR(11) NULL,
  `genero` VARCHAR(45) NULL,
  `nome_social` VARCHAR(45) NULL,
  `foto_perfil` MEDIUMBLOB NULL,
  `data_criacao` DATE NULL,
  `situacao` TINYINT(1) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social`.`amizade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social`.`amizade` (
  `idamizade` INT NOT NULL AUTO_INCREMENT,
  `idamizade_amigo` INT NOT NULL,
  `data_solicitacao` DATE NOT NULL,
  `data_confirmacao` DATE NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idamizade`, `idamizade_amigo`, `usuario_idusuario`),
  INDEX `fk_amizade_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_amizade_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social`.`albuns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social`.`albuns` (
  `idalbuns` INT NOT NULL AUTO_INCREMENT,
  `nome_foto` VARCHAR(100) NOT NULL,
  `local_foto` MEDIUMBLOB NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idalbuns`),
  UNIQUE INDEX `idalbuns_UNIQUE` (`idalbuns` ASC),
  INDEX `fk_albuns_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_albuns_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede-social`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede-social`.`postagem` (
  `idpostagem` INT NOT NULL AUTO_INCREMENT,
  `data_postagem` DATE NULL,
  `postagemtexto` LONGTEXT NULL,
  `postagem-fv` VARBINARY(60) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idpostagem`, `usuario_idusuario`),
  UNIQUE INDEX `idpostagem_UNIQUE` (`idpostagem` ASC),
  INDEX `fk_postagem_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rede-social`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
